### ISSUE TITLE
Add favicon and title to webpage

### ISSUE THREAD

**Issue by na933950** [PoliticalComputerScience/PCS-Website#29]
**Is your feature request related to a problem? Please describe.**
Yes, the current website icon and title in the actual tab are still the default Vite ones.

**Describe the solution you'd like**
Change the title to `PCS @ Berkeley` and the favicon to our logo. Make sure it is square.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Mockups**
![image](https://github.com/user-attachments/assets/db6004eb-194c-4e0d-bc49-643e8fccb69c)

But have it say `"PCS @ Berkeley"` instead.

**Flow**
N/A

**Comment by dexterousdhruv** [comment]
Hi @na933950! I've created a PR concerning the above mentioned issue. Please review it.
